project_id = "odlukohernadrwygjlfs"

[functions.generate-document]
verify_jwt = false

[functions.public-booking]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false
