// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.includes('<')) {
  throw new Error(
    [
      'Supabase não configurado. Defina VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no seu .env.',
      'Exemplo:',
      'VITE_SUPABASE_URL="https://<project-ref>.supabase.co"',
      'VITE_SUPABASE_PUBLISHABLE_KEY="<anon-key>"',
    ].join('\n')
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // sessionStorage: ao fechar o navegador, o usuário precisa logar novamente
    // (com fallback seguro para ambientes sem window, ex.: SSR/testes)
    storage: typeof window !== 'undefined' ? window.sessionStorage : undefined,
    persistSession: true,
    // não manter o usuário logado indefinidamente via refresh silencioso
    autoRefreshToken: false,
  },
});